spring:
  application:
    name: api-gateway

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:gatewaydb
    username: sa
    password:
    driver-class-name: org.h2.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: H2HikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true


  # KAFKA CONFIGURATION
  kafka:
    bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enable-idempotence: true
      retries: 10
      max.in-flight-requests-per-connection: 10
      batch-size: 16384
      linger-ms: 20
      buffer-memory: 33554432

server:
  port: 8085

discovery:
  user-service-url: http://localhost:8082
  order-service-url: http://localhost:8081
  user-service: user-service
  order-service: order-service

resilience4j:
  circuitbreaker:
    instances:
      order-service-circuit-breaker:
        registerHealthIndication: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 20
        waitDurationInOpenState: 60000
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      order-service-retry:
        maxRetryAttempts: 3
        waitDuration: 9s
  timelimiter:
    instances:
      order-service-timeout:
        timeoutDuration: 30s
  ratelimiter:
    instances:
      user-profile-rate-limiter:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms
      order-processor-rate-limiter:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 0ms

management:
  health:
    resilience4j:
      enabled: true
    circuitbreakers:
      order-service-circuit-breaker:
        enabled: true
      enabled: true
    metrics:
      order-service-circuit-breaker:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env,resilience4j
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    io.github.resilience4j: DEBUG
    io.micrometer: DEBUG
    org.springframework.boot.actuate.metrics: DEBUG
    org.springframework.security: TRACE
